
package Vista;

import Controladores.DietToDB;
import Modelos.Diet;
import Operaciones.ConnectionToDB;
import Operaciones.Validacion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




public class InternalDieta extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalDieta
     */
    
    
    public Connection link;
    public ConnectionToDB connection;
    public InternalDieta() {
        initComponents();
        connection = new ConnectionToDB();
        link = connection.getConnection();
        loadDiet();
    }
    public void cleanInfDiet(){
        txtNombreDieta.setText("");
        txtComidas.setText("");
    }
    
    public void loadDiet(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tblDietas.getModel();
        modeloTabla.setRowCount(0);
        DietToDB dietToDB = new DietToDB();
        ArrayList<Diet>Dietas = new ArrayList<>();
        Dietas = dietToDB.ReadDiets(link);

        for(Diet dieta: Dietas){
            Object[] dato = new Object[2];
            dato[0] = dieta.getNameRoutines();
            dato[1] = dieta.getTypeRoutine();
            modeloTabla.addRow(dato);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BD = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtNombreDieta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComidas = new javax.swing.JTextArea();
        lblMensaje = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDietas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        BD.setBackground(new java.awt.Color(22, 36, 71));
        BD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(22, 36, 71));

        btnModificar.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCrear.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Comidas");

        txtComidas.setColumns(20);
        txtComidas.setRows(5);
        jScrollPane2.setViewportView(txtComidas);

        lblMensaje.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 0, 51));

        btnBuscar.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNombreDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(btnBuscar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCrear))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(103, 103, 103)
                                            .addComponent(btnEliminar))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnModificar)
                                    .addGap(116, 116, 116))))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel3)
                .addContainerGap(330, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear)
                    .addComponent(btnBuscar))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar))
                .addGap(18, 18, 18)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        BD.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 530, 500));

        tblDietas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Comidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDietas);

        BD.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 590, 370));

        jPanel1.setBackground(new java.awt.Color(22, 36, 71));

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Dietas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        BD.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 60));

        btnCargar.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        BD.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        loadDiet();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        DietToDB dietaToDB = new DietToDB();
        Diet dieta = new Diet();
        if(dietaToDB.CountDietWhithName(link, txtNombreDieta.getText())>0)
        {
            dieta = dietaToDB.FoundDiet(link, txtNombreDieta.getText());
            txtComidas.setText("");
            for (String dietitas: dieta.getTypeRoutine()){
                txtComidas.append(dietitas + "\n");
            }
        }else{
            lblMensaje.setText("DIETA NO ENCONTRADA");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        DietToDB dietaToDB = new DietToDB();
        Diet dieta = new Diet();
        if(dietaToDB.CountDietWhithName(link, txtNombreDieta.getText())>0)
        {
            dieta = dietaToDB.FoundDiet(link, txtNombreDieta.getText());
            int answer = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la dieta?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (answer == JOptionPane.YES_OPTION) {
                dietaToDB.DeleteDiet(link, dieta);

                if( dietaToDB.CountDietWhithName(link, txtNombreDieta.getText())==0){
                    lblMensaje.setText("DATOS ELIMINADOS");
                    loadDiet();
                    cleanInfDiet();
                }else{
                    JOptionPane.showMessageDialog(null, "NO SE PUDO ELIMINAR\n¡¡EXISTE MAS DE UN USUARIO CON ESTA DIETA!!", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            }else{
                lblMensaje.setText("CANCELADO");

            }
        }else{
            lblMensaje.setText("DIETA NO ENCONTRADA");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        //Actualmente esta guardando unicamente el nombre de la dieta, pero no las comidas
        DietToDB dieta = new DietToDB();
        Diet consultaDieta = dieta.FoundDiet(link, txtNombreDieta.getText());
        Validacion val = new Validacion();
        if(!txtNombreDieta.getText().isEmpty())
        {
            if(dieta.CountDietWhithName(link, txtNombreDieta.getText()) == 0){
                String nombre = txtNombreDieta.getText();
                ArrayList<String> comidas = new ArrayList();
                String[] StringComidas = txtComidas.getText().split("\\n");
                for(String comida : StringComidas){
                    comidas.add(comida);
                }

                if(comidas.size()>0 && !comidas.get(0).isEmpty()){
                    //Verificar que el nombre no se repita
                    consultaDieta.setNameRoutines(nombre);
                    //Verificar que haya almenos una comida en el arreglo de comidas ingresadas
                    consultaDieta.setTypeRoutine(comidas);
                    if(dieta.CreateDiet(link, consultaDieta)){
                        cleanInfDiet();
                        loadDiet();
                        lblMensaje.setText("DATOS CREADOS");
                    }else{
                        lblMensaje.setText("NO SE PUDIERON CREAR LOS DATOS");
                    }

                }else{
                    lblMensaje.setText("NO SE HAN INGRESADO COMIDAS");

                }
            }else{
                lblMensaje.setText("EL NOMBRE DE LA DIETA YA EXISTE");
            }
        }else{
            lblMensaje.setText("INGRESA UN NOMBRE PARA LA DIETA");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        DietToDB dietaToDB = new DietToDB();
        Diet dieta = dietaToDB.FoundDiet(link, txtNombreDieta.getText());
        if(dietaToDB.CountDietWhithName(link, txtNombreDieta.getText()) > 0){
            String nombre = txtNombreDieta.getText();
            ArrayList<String> comidas = new ArrayList();
            String[] StringComidas = txtComidas.getText().split("\\n");
            for(String comida : StringComidas){

                comidas.add(comida);
            }

            if(comidas.size() > 1){
                //Verificar que el nombre no se repita
                dieta.setNameRoutines(nombre);
                //Verificar que haya almenos una comida en el arreglo de comidas ingresadas
                dieta.setTypeRoutine(comidas);
                if(dietaToDB.UpdateDiet(link, dieta)){
                    cleanInfDiet();
                    loadDiet();
                    lblMensaje.setText("DATOS MODIFICADOS CORRECTAMENTE");
                }
            }
        }else{
            lblMensaje.setText("DIETA NO ENCONTRADA");
        }
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BD;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTable tblDietas;
    private javax.swing.JTextArea txtComidas;
    private javax.swing.JTextField txtNombreDieta;
    // End of variables declaration//GEN-END:variables
}
