
package Vista;

import Controladores.*;
import Modelos.Usuario;
import Modelos.Diet;
import Modelos.Routine;
import Operaciones.*;
import com.toedter.calendar.JCalendar;

import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


public class InternalRutina extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalRutina
     */
    
    
    public ConnectionToDB conexion;
    public Connection link;
    public InternalRutina() {
        initComponents();
        
        conexion=new ConnectionToDB();
        link=conexion.getConnection();
    }
    
    public void cleanInfRoutine(){
            txtNombreRutina.setText("");
            txtEjercicio.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BD = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRutinas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtNombreRutina = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEjercicio = new javax.swing.JTextArea();
        lblMensaje = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();

<<<<<<< HEAD
        setBackground(new java.awt.Color(22, 36, 71));
        setClosable(true);
        setMaximizable(true);
=======
        setClosable(true);
>>>>>>> d7420cca9413303f5e35b5105354a0c6e688421f
        setResizable(true);

        BD.setBackground(new java.awt.Color(22, 36, 71));
        BD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRutinas.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        tblRutinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Ejercicio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRutinas);

        BD.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 490, 370));

        jPanel2.setBackground(new java.awt.Color(22, 36, 71));

<<<<<<< HEAD
=======
        txtNombreRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRutinaActionPerformed(evt);
            }
        });

>>>>>>> d7420cca9413303f5e35b5105354a0c6e688421f
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Nombre ");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Ejercicios");

        btnModificar.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCrear.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtEjercicio.setColumns(20);
        txtEjercicio.setRows(5);
        jScrollPane2.setViewportView(txtEjercicio);

        lblMensaje.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 0, 51));

        btnBuscar.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
<<<<<<< HEAD
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(338, 338, 338))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnModificar)
                                            .addComponent(btnBuscar))
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCrear)
                                            .addComponent(btnEliminar))))
                                .addGap(166, 166, 166))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
=======
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(338, 338, 338))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificar)
                                    .addComponent(btnBuscar))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCrear)
                                    .addComponent(btnEliminar))))
                        .addGap(155, 155, 155))))
>>>>>>> d7420cca9413303f5e35b5105354a0c6e688421f
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(147, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombreRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))
                        .addGap(27, 27, 27)))
=======
                .addGap(163, 163, 163)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(27, 27, 27)
>>>>>>> d7420cca9413303f5e35b5105354a0c6e688421f
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        BD.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 300, 500));

        jPanel1.setBackground(new java.awt.Color(22, 36, 71));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Rutinas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        BD.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 60));

        btnCargar.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        BD.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
=======
    private void txtNombreRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRutinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreRutinaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        RoutineToDB rutinaToDB = new RoutineToDB();
        Routine rutina = rutinaToDB.FoundRoutine(link, txtNombreRutina.getText());
        try {
            if(rutinaToDB.contarRutinas(link, txtNombreRutina.getText()) > 0){
                String nombre = txtNombreRutina.getText();
                ArrayList<String> ejercicios = new ArrayList();
                String[] StringEjercicios = txtEjercicio.getText().split("\\n");
                for(String ejercicio : StringEjercicios){

                    ejercicios.add(ejercicio);
                }

                if(ejercicios.size() > 1){
                    //Verificar que el nombre no se repita
                    rutina.setNameRoutines(nombre);
                    //Verificar que haya almenos una comida en el arreglo de comidas ingresadas
                    rutina.setTypeRoutine(ejercicios);
                    if(rutinaToDB.UpdateRoutine(link, rutina)){
                        cleanInfRoutine();
                        lblMensaje.setText("DATOS CREADOS");
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelDieta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        RoutineToDB rutina = new RoutineToDB();
        Routine consultaRutina = rutina.FoundRoutine(link, txtNombreRutina.getText());
        Validacion val = new Validacion();

        try {
            if(rutina.contarRutinas(link, txtNombreRutina.getText()) == 0){
                String nombreRutina = txtNombreRutina.getText();
                ArrayList<String> ejercicios = new ArrayList();
                String[] StringEjercicios = txtEjercicio.getText().split("\\n");
                for(String ejercicio : StringEjercicios){

                    ejercicios.add(ejercicio);
                }

                if(ejercicios.size() > 1){
                    //Verificar que el nombre no se repita
                    consultaRutina.setNameRoutines(nombreRutina);
                    //Verificar que haya almenos una comida en el arreglo de comidas ingresadas
                    consultaRutina.setTypeRoutine(ejercicios);
                    if(rutina.CreateRoutine(link, consultaRutina)){
                        cleanInfRoutine();
                        lblMensaje.setText("DATOS CREADOS");
                    }else{
                        lblMensaje.setText("NO SE PUDIERON CREAR LOS DATOS");
                    }

                }else{
                    lblMensaje.setText("NO SE HAN INGRESADO EJERCICIOS");

                }
            }else{
                lblMensaje.setText("EL NOMBRE DE LA RUTINA YA EXISTE");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelDieta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        RoutineToDB rutinaToDB = new RoutineToDB();
        Routine rutina = new Routine();
        rutina = rutinaToDB.FoundRoutine(link, txtNombreRutina.getText());
        if(rutina!=null){
            int answer = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la rutina?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (answer == JOptionPane.YES_OPTION) {
                rutinaToDB.DeleteRoutine(link, rutina);
                lblMensaje.setText("DATOS ELIMINADOS");
            }else{
                lblMensaje.setText("CANCELADO");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        RoutineToDB rutinaToDB = new RoutineToDB();
        Routine rutina = new Routine();
        rutina = rutinaToDB.FoundRoutine(link, txtNombreRutina.getText());
        txtEjercicio.setText("");
        for (String dietitas: rutina.getTypeRoutine()){
            txtEjercicio.append(dietitas + "\n");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

>>>>>>> d7420cca9413303f5e35b5105354a0c6e688421f
    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modeloTabla = (DefaultTableModel) tblRutinas.getModel();
        modeloTabla.setRowCount(0);
        RoutineToDB rutinaToDB = new RoutineToDB();
        ArrayList<Routine>rutinas = new ArrayList<>();
        rutinas = rutinaToDB.ReadRoutines(link);

        for(Routine rutina : rutinas){
            Object[] dato = new Object[2];
            dato[0] = rutina.getNameRoutines();
            dato[1] = rutina.getTypeRoutine();
            modeloTabla.addRow(dato);
        }

    }//GEN-LAST:event_btnCargarActionPerformed

<<<<<<< HEAD
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        RoutineToDB rutinaToDB = new RoutineToDB();
        Routine rutina = new Routine();
        rutina = rutinaToDB.FoundRoutine(link, txtNombreRutina.getText());
        if(rutinaToDB.CountRoutineWhithName(link, txtNombreRutina.getText())>0){
            txtEjercicio.setText("");
            for (String dietitas: rutina.getTypeRoutine()){
                txtEjercicio.append(dietitas + "\n");
            }
        }else{
            lblMensaje.setText("RUTINA NO ENCONTRADA");
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        RoutineToDB rutinaToDB = new RoutineToDB();
        Routine rutina = new Routine();
        rutina = rutinaToDB.FoundRoutine(link, txtNombreRutina.getText());
        if(rutinaToDB.CountRoutineWhithName(link, txtNombreRutina.getText())>0){
            int answer = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la rutina?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (answer == JOptionPane.YES_OPTION) {
                rutinaToDB.DeleteRoutine(link, rutina);
                if(rutinaToDB.CountRoutineWhithName(link, txtNombreRutina.getText())==0){
                    lblMensaje.setText("DATOS ELIMINADOS");
                    cleanInfRoutine();
                }else{
                    JOptionPane.showMessageDialog(null, "NO SE PUDO ELIMINAR\n¡¡EXISTE MAS DE UN USUARIO CON ESTA RUTINA!!", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            }else{
                lblMensaje.setText("CANCELADO");
            }
        }else{
            lblMensaje.setText("RUTINA NO ENCONTRADA");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        RoutineToDB rutina = new RoutineToDB();
        Routine consultaRutina = rutina.FoundRoutine(link, txtNombreRutina.getText());
        Validacion val = new Validacion();
        if(!txtNombreRutina.getText().isEmpty())
        {
            if(rutina.CountRoutineWhithName(link, txtNombreRutina.getText()) == 0 ){
                String nombreRutina = txtNombreRutina.getText();
                ArrayList<String> ejercicios = new ArrayList();
                String[] StringEjercicios = txtEjercicio.getText().split("\\n");
                for(String ejercicio : StringEjercicios)
                {
                    ejercicios.add(ejercicio);
                }
                if(ejercicios.size()>1 && !ejercicios.get(0).isEmpty())
                {
                    //Verificar que el nombre no se repita
                    consultaRutina.setNameRoutines(nombreRutina);
                    //Verificar que haya almenos una comida en el arreglo de comidas ingresadas
                    consultaRutina.setTypeRoutine(ejercicios);
                    if(rutina.CreateRoutine(link, consultaRutina))
                    {
                        cleanInfRoutine();
                        lblMensaje.setText("DATOS CREADOS");
                    }else{
                        lblMensaje.setText("NO SE PUDIERON CREAR LOS DATOS");
                    }
                }else{
                    lblMensaje.setText("NO SE HAN INGRESADO EJERCICIOS");
                }
            }else{
                lblMensaje.setText("EL NOMBRE DE LA RUTINA YA EXISTE");
            }
        }else{
            lblMensaje.setText("INGRESA UN NOMBRE PARA LA RUTINA");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        RoutineToDB rutinaToDB = new RoutineToDB();
        Routine rutina = rutinaToDB.FoundRoutine(link, txtNombreRutina.getText());
        if(rutinaToDB.CountRoutineWhithName(link, txtNombreRutina.getText()) > 0){
            String nombre = txtNombreRutina.getText();
            ArrayList<String> ejercicios = new ArrayList();
            String[] StringEjercicios = txtEjercicio.getText().split("\\n");
            for(String ejercicio : StringEjercicios){

                ejercicios.add(ejercicio);
            }

            if(ejercicios.size() > 1){
                //Verificar que el nombre no se repita
                rutina.setNameRoutines(nombre);
                //Verificar que haya almenos una comida en el arreglo de comidas ingresadas
                rutina.setTypeRoutine(ejercicios);
                if(rutinaToDB.UpdateRoutine(link, rutina)){
                    cleanInfRoutine();
                    lblMensaje.setText("DATOS MODIFICADOS CORRECTAMENTE");
                }
            }
        }else{
            lblMensaje.setText("RUTINA NO ENCONTRADA");

        }
    }//GEN-LAST:event_btnModificarActionPerformed

=======
>>>>>>> d7420cca9413303f5e35b5105354a0c6e688421f

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BD;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTable tblRutinas;
    private javax.swing.JTextArea txtEjercicio;
    private javax.swing.JTextField txtNombreRutina;
    // End of variables declaration//GEN-END:variables
}
