/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Acer
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        menuDietas = new javax.swing.JMenu();
        menuRutinas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(22, 36, 71));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(0, 153, 153));
        jMenuBar1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N

        menuUsuarios.setText("Usuarios");
        menuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUsuariosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuUsuarios);

        menuDietas.setText("Dietas");
        menuDietas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDietasMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDietas);

        menuRutinas.setText("Rutinas");
        menuRutinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRutinasMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRutinas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuariosMouseClicked
        
        //PanelUsuario panelUsuario = new PanelUsuario();
        //panelUsuario.setVisible(true);
        
        InternalUsuario Usuario = new InternalUsuario();
        Usuario.setVisible(true);
        this.add(Usuario);
        
        try {
           Usuario.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
        
    }//GEN-LAST:event_menuUsuariosMouseClicked

    private void menuDietasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDietasMouseClicked
        //PanelDieta panelDieta = new PanelDieta();
        //panelDieta.setVisible(true);
        
        InternalDieta dieta = new InternalDieta();
        dieta.setVisible(true);
        this.add(dieta);
        
        try {
           dieta.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
        
    }//GEN-LAST:event_menuDietasMouseClicked

    private void menuRutinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRutinasMouseClicked
        //PanelRutina panelRutina = new PanelRutina();
        //panelRutina.setVisible(true);
        InternalRutina rutina = new InternalRutina();
        rutina.setVisible(true);
        this.add(rutina);
        
        try {
           rutina.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
        
        
    }//GEN-LAST:event_menuRutinasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuDietas;
    private javax.swing.JMenu menuRutinas;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
